#ifndef __INC_AFFECT_H
#define __INC_AFFECT_H

class CAffect
{
	public:
		DWORD	dwType;
		BYTE    bApplyOn;
		long    lApplyValue;
		DWORD   dwFlag;
		long	lDuration;
		long	lSPCost;

		static CAffect* Acquire();
		static void Release(CAffect* p);
};

enum EAffectTypes
{
	AFFECT_NONE,

	AFFECT_MOV_SPEED		= 200,
	AFFECT_ATT_SPEED,
	AFFECT_ATT_GRADE,
	AFFECT_INVISIBILITY,
	AFFECT_STR,
	AFFECT_DEX,			// 205
	AFFECT_CON,
	AFFECT_INT,
	AFFECT_FISH_MIND_PILL,

	AFFECT_POISON,
	AFFECT_STUN,		// 210
	AFFECT_SLOW,
	AFFECT_DUNGEON_READY,
	AFFECT_DUNGEON_UNIQUE,

	AFFECT_BUILDING,
	AFFECT_REVIVE_INVISIBLE,	// 215
	AFFECT_FIRE,
	AFFECT_CAST_SPEED,
	AFFECT_HP_RECOVER_CONTINUE,
	AFFECT_SP_RECOVER_CONTINUE,

	AFFECT_POLYMORPH,		// 220
	AFFECT_MOUNT,

	AFFECT_WAR_FLAG,		// 222

	AFFECT_BLOCK_CHAT,		// 223
	AFFECT_CHINA_FIREWORK,

	AFFECT_BOW_DISTANCE,	// 225
	AFFECT_DEF_GRADE,		// 226
#ifdef OFFLINE_SHOP
	AFFECT_SHOPOWNER = 227,
#endif
#ifdef NEW_PET_SYSTEM
	AFFECT_PET,
#endif
#ifdef ENABLE_WOLFMAN_CHARACTER
	AFFECT_BLEEDING,		// 227
#endif

	AFFECT_PREMIUM_START	= 500,
	AFFECT_EXP_BONUS		= 500,	// ������ ����
	AFFECT_ITEM_BONUS		= 501,	// ������ �尩
	AFFECT_SAFEBOX		= 502,  // PREMIUM_SAFEBOX,
	AFFECT_AUTOLOOT		= 503,	// PREMIUM_AUTOLOOT,
	AFFECT_FISH_MIND		= 504,	// PREMIUM_FISH_MIND,
	AFFECT_MARRIAGE_FAST	= 505,	// ������ ����
	AFFECT_GOLD_BONUS		= 506,	// �� ���Ȯ�� 50%����
	AFFECT_PREMIUM_END		= 509,

	AFFECT_MALL			= 510,	// �� ������ ����Ʈ
	AFFECT_NO_DEATH_PENALTY	= 511,	// ����� ��ȣ (����ġ�� �г�Ƽ�� �ѹ� �����ش�)
	AFFECT_SKILL_BOOK_BONUS	= 512,	// ������ ���� (å ���� ���� Ȯ���� 50% ����)
	AFFECT_SKILL_NO_BOOK_DELAY	= 513,	// �־ȼ���

	AFFECT_HAIR	= 514,	// ��� ȿ��
	AFFECT_COLLECT = 515, //��������Ʈ
	AFFECT_EXP_BONUS_EURO_FREE = 516, // ������ ���� (���� ���� 14 ���� ���� �⺻ ȿ��)
	AFFECT_EXP_BONUS_EURO_FREE_UNDER_15 = 517,
	AFFECT_UNIQUE_ABILITY = 518,

	AFFECT_CUBE_1,
	AFFECT_CUBE_2,
	AFFECT_CUBE_3,
	AFFECT_CUBE_4,
	AFFECT_CUBE_5,
	AFFECT_CUBE_6,
	AFFECT_CUBE_7,
	AFFECT_CUBE_8,
	AFFECT_CUBE_9,
	AFFECT_CUBE_10,
	AFFECT_CUBE_11,
	AFFECT_CUBE_12,

	AFFECT_BLEND,

	AFFECT_HORSE_NAME,
	AFFECT_MOUNT_BONUS,
#ifdef ENABLE_AFK_MODE_SYSTEM
	AFFECT_AFK = 231,
#endif
#ifdef NEW_PET_SYSTEM
	AFFECT_NEW_PET = 559,
#endif
	AFFECT_AUTO_HP_RECOVERY = 534,
	AFFECT_AUTO_SP_RECOVERY = 535,
	AFFECT_DRAGON_SOUL_QUALIFIED = 540,
	AFFECT_DRAGON_SOUL_DECK_0 = 541,
	AFFECT_DRAGON_SOUL_DECK_1 = 542,
#ifndef ENABLE_RENEWAL_PVP
	AFFECT_PVP_START = 546,
#endif
#ifdef __SPECIALSTAT_SYSTEM__
	AFFECT_SPECIAL_STAT1 = 550,
	AFFECT_SPECIAL_STAT2 = 551,
	AFFECT_SPECIAL_STAT3 = 552,
	AFFECT_SPECIAL_STAT4 = 553,
	AFFECT_SPECIAL_STAT5 = 554,
	AFFECT_SPECIAL_STAT6 = 555,
#endif

#ifdef ENABLE_BIOLOG_SYSTEM
	AFF_BIO_1 = 643,	AFF_BIO_2 = 644,	AFF_BIO_3 = 645,	AFF_BIO_4 = 646,
	AFF_BIO_5 = 647,	AFF_BIO_6 = 648,	AFF_BIO_7 = 649,	AFF_BIO_8 = 650,
	AFF_BIO_9 = 651,	AFF_BIO_10 = 652,	AFF_BIO_11 = 653,	AFF_BIO_12 = 654,
	AFF_BIO_13 = 655,	AFF_BIO_14 = 656,	AFF_BIO_15 = 657,	AFF_BIO_16 = 658,
	AFF_BIO_17 = 659,	AFF_BIO_18 = 660,	AFF_BIO_19 = 661,	AFF_BIO_20 = 662,
#endif


	AFFECT_RAMADAN_ABILITY = 300,
	AFFECT_RAMADAN_RING	   = 301,

	AFFECT_NOG_ABILITY = 302,
	AFFECT_HOLLY_STONE_POWER = 303,
	
#ifdef ENABLE_OVER_KILL
	AFFECT_OVER_KILL_FURY = 304,
#endif

#ifdef ENABLE_SPECIAL_AFFECT
	AFFECT_SPECIAL_AFFECT_PLAYER_1ST = 700,
	AFFECT_SPECIAL_AFFECT_PLAYER_2ND,
	AFFECT_SPECIAL_AFFECT_PLAYER_3RD,
	AFFECT_SPECIAL_AFFECT_GUILD_1ST,
	AFFECT_SPECIAL_AFFECT_GUILD_2ND,
	AFFECT_SPECIAL_AFFECT_GUILD_3RD,
#endif


#ifdef ENABLE_DECORUM
	AFFECT_DECORUM				= 716,
	AFFECT_NO_LOSS_DECORUM		= 717,
	AFFECT_GAIN_DECORUM			= 718,
#endif

#ifdef M2S_BIO_SYSTEM
	AFFECT_BIO = 620,
#endif
#ifdef ENABLE_RENEWAL_PVP
	AFFECT_PVP_SETTINGS = 777,
#endif

#ifdef ENABLE_MELEY_LAIR_DUNGEON
	AFFECT_STATUE = 778,
#endif

#ifdef ENABLE_NEW_AFFECT_POTION	
	AFFECT_POTION_1 = 779,
	AFFECT_POTION_2 = 780,
	AFFECT_POTION_3 = 781,
	AFFECT_POTION_4 = 782,
	AFFECT_POTION_5 = 783,
	AFFECT_POTION_6 = 784,
#endif
#if defined(__SHIP_DEFENSE__)
	AFFECT_DEFENSEWAVE_LASER = 785,
#endif
	AFFECT_QUEST_START_IDX = 1000
};

enum EAffectBits
{
	AFF_NONE,

	AFF_YMIR,
	AFF_INVISIBILITY,
	AFF_SPAWN,

	AFF_POISON,
	AFF_SLOW,
	AFF_STUN,

	AFF_DUNGEON_READY,		// �������� �غ� ����
	AFF_DUNGEON_UNIQUE,		// ���� ����ũ (Ŭ���̾�Ʈ���� �ø���������)

	AFF_BUILDING_CONSTRUCTION_SMALL,
	AFF_BUILDING_CONSTRUCTION_LARGE,
	AFF_BUILDING_UPGRADE,

	AFF_MOV_SPEED_POTION,
	AFF_ATT_SPEED_POTION,

	AFF_FISH_MIND,

	AFF_JEONGWIHON,		// ����ȥ
	AFF_GEOMGYEONG,		// �˰�
	AFF_CHEONGEUN,		// õ����
	AFF_GYEONGGONG,		// �����
	AFF_EUNHYUNG,		// ������
	AFF_GWIGUM,			// �Ͱ�
	AFF_TERROR,			// ����
	AFF_JUMAGAP,		// �ָ���
	AFF_HOSIN,			// ȣ��
	AFF_BOHO,			// ��ȣ
	AFF_KWAESOK,		// ���
	AFF_MANASHIELD,		// ��������
	AFF_MUYEONG,		// ������ affect
	AFF_REVIVE_INVISIBLE,	// ��Ȱ�� ��õ��� ����
	AFF_FIRE,			// ���� �� ������
	AFF_GICHEON,		// ��õ���
	AFF_JEUNGRYEOK,		// ���¼�
	AFF_TANHWAN_DASH,		// źȯ�ݿ� �޸������Ʈ
	AFF_PABEOP,			// �Ĺ���
	AFF_CHEONGEUN_WITH_FALL,	// õ����
	AFF_POLYMORPH,
	AFF_WAR_FLAG1,
	AFF_WAR_FLAG2,
	AFF_WAR_FLAG3,
#ifdef ENABLE_AFK_MODE_SYSTEM
	AFF_AFK,
#endif
	AFF_CHINA_FIREWORK,
	AFF_HAIR,	// ���
	AFF_GERMANY, // ����
	AFF_RAMADAN_RING,
#ifdef ENABLE_WOLFMAN_CHARACTER
	AFF_BLEEDING,			// 42
	AFF_RED_POSSESSION,		// 44
	AFF_BLUE_POSSESSION,	// 43
#endif
#ifdef OFFLINE_SHOP
	AFF_SHOPOWNER,
#endif
#ifdef ENABLE_OVER_KILL
	AFF_OVER_KILL_FURY,
#endif
#ifdef ENABLE_SPECIAL_AFFECT
	AFF_SPECIAL_AFFECT_PLAYER_1ST,
	AFF_SPECIAL_AFFECT_PLAYER_2ND,
	AFF_SPECIAL_AFFECT_PLAYER_3RD,
	AFF_SPECIAL_AFFECT_GUILD_1ST,
	AFF_SPECIAL_AFFECT_GUILD_2ND,
	AFF_SPECIAL_AFFECT_GUILD_3RD,
#endif
#ifdef ENABLE_DS_ACTIVE_LOOP
	AFF_DS_ACTIVE,
#endif
	#ifdef ENABLE_MELEY_LAIR_DUNGEON
	AFF_STATUE1,
	AFF_STATUE2,
	AFF_STATUE3,
	AFF_STATUE4,
	#endif
#ifdef ITEM_BUFF_SYSTEM
	AFF_RESIST_BUFF,		
	AFF_CRITICAL_BUFF,		
	AFF_REFLECT_BUFF,		
#endif
#if defined(__SHIP_DEFENSE__)
	AFF_DEFENSE_WAVE_LASER,
#endif
	AFF_BITS_MAX
};

extern void SendAffectAddPacket(LPDESC d, CAffect * pkAff);

// AFFECT_DURATION_BUG_FIX
enum AffectVariable
{
	// Affect�� ���Ѵ�� �� �־�� �� ��� ���.
	// �ð��� ��� ���̱� ������ �ſ� ū������ ���Ѵ븦 ���ķ��̼���.
	//// 24��Ʈ�� �����Ƿ� 25��Ʈ�� ���.
	// ... 25��Ʈ ����Ѵٰ� �س����� 29bit ����ϰ� �ִ� ��û�� �ּ��̶�...
	// collect quest���� ���� �ð��� 60������ ����ϰ� �����Ƿ�, ���⵵ 60������ ����.

	INFINITE_AFFECT_DURATION = 60 * 365 * 24 * 60 * 60
};
// END_AFFECT_DURATION_BUG_FIX

#endif
