#ifndef __INC_METIN_II_LENGTH_H__
#define __INC_METIN_II_LENGTH_H__

#include "CommonDefines.h"
#include "service.h"

#define WORD_MAX 0xffff
enum EMisc
{
	MAX_HOST_LENGTH			= 15,
	IP_ADDRESS_LENGTH		= 15,
	LOGIN_MAX_LEN			= 30,
	PASSWD_MAX_LEN			= 16,
#ifdef ENABLE_PLAYER_PER_ACCOUNT5
	PLAYER_PER_ACCOUNT		= 5,
#else
	PLAYER_PER_ACCOUNT		= 4,
#endif
	ACCOUNT_STATUS_MAX_LEN	= 8,
	CHARACTER_NAME_MAX_LEN	= 24,
	SHOP_SIGN_MAX_LEN		= 32,
	INVENTORY_PAGE_COLUMN	= 5, // 5 (default)
	INVENTORY_PAGE_ROW		= 9, // 9 (default)
	INVENTORY_PAGE_SIZE		= INVENTORY_PAGE_COLUMN*INVENTORY_PAGE_ROW,
#ifdef ENABLE_EXTEND_INVEN_SYSTEM
	INVENTORY_PAGE_COUNT	= 4, // 2 (default)
#else
	INVENTORY_PAGE_COUNT	= 2, // 2 (default)
#endif
	INVENTORY_MAX_NUM		= INVENTORY_PAGE_SIZE*INVENTORY_PAGE_COUNT, // 90 (default)
	ABILITY_MAX_NUM			= 50,
	EMPIRE_MAX_NUM			= 4,
	BANWORD_MAX_LEN			= 24,
	SMS_MAX_LEN				= 80,
	MOBILE_MAX_LEN			= 32,
	SOCIAL_ID_MAX_LEN		= 18,

	GUILD_NAME_MAX_LEN		= 12,
#ifdef OFFLINE_SHOP
	OFFLINE_SHOP_HOST_ITEM_MAX_NUM = 64,
#endif
	SHOP_HOST_ITEM_MAX_NUM	= 80,	/* ȣ��Ʈ�� �ִ� ������ ���� */
	SHOP_GUEST_ITEM_MAX_NUM = 18,	/* �Խ�Ʈ�� �ִ� ������ ���� */

	SHOP_PRICELIST_MAX_NUM	= 40,	///< ���λ��� �������� ����Ʈ���� ������ ���������� �ִ� ����

	CHAT_MAX_LEN			= 512,

	QUICKSLOT_MAX_NUM		= 36,

	JOURNAL_MAX_NUM			= 2,

	QUERY_MAX_LEN			= 8192,

	FILE_MAX_LEN			= 128,

	PLAYER_EXP_TABLE_MAX	= 120,
	PLAYER_MAX_LEVEL_CONST	= 250,
	
	#ifdef ENABLE_MULTI_LANGUAGE_SYSTEM
	LANGUAGE_MAX_LEN		= 2,
	LANGUAGE_MAX_NUM		= 6,
	#endif

	GUILD_MAX_LEVEL			= 20,
	MOB_MAX_LEVEL			= 100,
#if defined(__BL_SOUL_ROULETTE__)
	ROULETTE_ITEM_MAX		= 20,
#endif
	ATTRIBUTE_MAX_VALUE		= 20,
	CHARACTER_PATH_MAX_NUM	= 64,
	SKILL_MAX_NUM			= 255,
	SKILLBOOK_DELAY_MIN		= 1,
	SKILLBOOK_DELAY_MAX		= 2,
	SKILL_MAX_LEVEL			= 40,

	APPLY_NAME_MAX_LEN		= 32,
	EVENT_FLAG_NAME_MAX_LEN = 32,

	MOB_SKILL_MAX_NUM		= 5,

    POINT_MAX_NUM = 255,
	DRAGON_SOUL_BOX_SIZE = 32,
#ifdef ENABLE_EXTENDED_DS_INVENTORY
	DRAGON_SOUL_INVENTORY_PAGE_COUNT = 3,
#endif
	DRAGON_SOUL_BOX_COLUMN_NUM = 8,
	DRAGON_SOUL_BOX_ROW_NUM = DRAGON_SOUL_BOX_SIZE / DRAGON_SOUL_BOX_COLUMN_NUM,
	DRAGON_SOUL_REFINE_GRID_SIZE = 15,
	MAX_AMOUNT_OF_MALL_BONUS	= 20,

#if defined(ENABLE_NEW_TALISMAN_SLOTS_NEW) || defined(ENABLE_NEW_TALISMAN_SLOTS)
	WEAR_MAX_NUM				= 60,
#else
	WEAR_MAX_NUM				= 32,
#endif

#ifdef ENABLE_GEM_SYSTEM
	GEM_SLOTS_MAX_NUM 			= 9,
	GEM_REFRESH_ITEM_VNUM 		= 39063,
	GEM_UNLOCK_ITEM_VNUM 		= 39064,
	GEM_GLIMMERSTONE_VNUM		= 50926,
	GEM_REFRESH_PULSE			= 5, //hours
	GEM_MAX 					= 1000000,
#endif

	//LIMIT_GOLD
	//GOLD_MAX = 2000000000,
	GOLD_MAX = 2100000000,
#ifdef ENABLE_CHEQUE_SYSTEM
	CHEQUE_MAX = 999,
#endif
	MAX_PASSPOD = 8 ,
#ifdef ENABLE_6_7_BONUS_NEW_SYSTEM
	c_skillbook_slot_max = 10,
	GOLD_COMB_SKILLBOOK = 100000,
	BONUS_67_SLOT_MAX = 1,
#endif

	//END_LIMIT_GOLD

	OPENID_AUTHKEY_LEN = 32,

	SHOP_TAB_NAME_MAX = 32,
	SHOP_TAB_COUNT_MAX = 3,

	BELT_INVENTORY_SLOT_WIDTH = 4,
	BELT_INVENTORY_SLOT_HEIGHT= 4,

	BELT_INVENTORY_SLOT_COUNT = BELT_INVENTORY_SLOT_WIDTH * BELT_INVENTORY_SLOT_HEIGHT,

#ifdef __SPECIAL_STORAGE_SYSTEM__
	SPECIAL_STORAGE_INVENTORY_PAGE_COLUMN	= 5, // 5 (default)
	SPECIAL_STORAGE_INVENTORY_PAGE_ROW		= 9, // 9 (default)
	SPECIAL_STORAGE_INVENTORY_PAGE_SIZE		= SPECIAL_STORAGE_INVENTORY_PAGE_COLUMN * SPECIAL_STORAGE_INVENTORY_PAGE_ROW,
	SPECIAL_STORAGE_INVENTORY_PAGE_COUNT	= 4, // 4 (default)
	SPECIAL_STORAGE_INVENTORY_MAX_NUM		= 180,
#endif
#ifdef ENABLE_OVER_KILL	
	OVER_KILL_MAX_NUM = 5,//max num of effect (double kill , triple kill ecc.)
#endif
#ifdef WON_EXCHANGE
	//CHEQUE_MAX = 999,
	TAX_MUL = 3,
	CHEQUE_NAME_VALUE = 100000000,
#endif
#ifdef ENABLE_DECORUM
	DECORUM_WEEKLY_KILLS		= 7,
#endif

/**
	 **** ������� �Ҵ� �� ������ ���� ���� (DB�� Item Position) ****
	+------------------------------------------------------+ 0
	| ĳ���� �⺻ �κ��丮 (45ĭ * 2������) 90ĭ           |
	+------------------------------------------------------+ 90 = INVENTORY_MAX_NUM(90)
	| ĳ���� ��� â (�������� ������) 32ĭ                |
	+------------------------------------------------------+ 122 = INVENTORY_MAX_NUM(90) + WEAR_MAX_NUM(32)
	| ��ȥ�� ��� â (�������� ��ȥ��) 12ĭ                |
	+------------------------------------------------------+ 134 = 122 + DS_SLOT_MAX(6) * DRAGON_SOUL_DECK_MAX_NUM(2)
	| ��ȥ�� ��� â ���� (���� �̻��) 18ĭ               |
	+------------------------------------------------------+ 152 = 134 + DS_SLOT_MAX(6) * DRAGON_SOUL_DECK_RESERVED_MAX_NUM(3)
	| ��Ʈ �κ��丮 (��Ʈ ����ÿ��� ��Ʈ ������ ���� Ȱ��)|
	+------------------------------------------------------+ 168 = 152 + BELT_INVENTORY_SLOT_COUNT(16) = INVENTORY_AND_EQUIP_CELL_MAX
	| �̻��                                               |
	+------------------------------------------------------+ ??
*/
};

#ifdef ENABLE_SWITCHBOT

enum SwitchbotValues
{
	SWITCHBOT_SLOT_COUNT = 3,
	SWITCHBOT_ALTERNATIVE_COUNT = 2,
	//1 = Switching Item
	//2 = Yang
	SWITCHBOT_PRICE_TYPE = 1,
	//Amount Swtichting Items the Yang-Price
	SWITCHBOT_PRICE_AMOUNT = 1,
};

const DWORD c_arSwitchingItems[2] =
{
	71151,
	11074,
};
#endif

#ifdef ENABLE_NEW_DETAILS_GUI
enum
{
	KILL_SHINSO,
	KILL_JINNO,
	KILL_CHUNJO,
	KILL_ALLPLAYER,
	KILL_DUELWON,
	KILL_DUELLOST,
	KILL_MONSTERS,
	KILL_METINSTONE,
	KILL_BOSSES,
	KILL_MAX_NUM,
};
#endif

enum EMatrixCard
{
	MATRIX_CODE_MAX_LEN		= 192,
	MATRIX_ANSWER_MAX_LEN	= 8,
};

const int SPECIALSTAT_SKILLBOOK_TIME_SKIP = 58999;
const int SPECIALSTAT_SKILLBOOK_TIME_SKIP_PROB = 70;
const int SPECIALSTAT_SKILLBOOK_PROB = 48;
const int SPECIALSTAT_SKILLBOOK_START = 59000;
const int SPECIALSTAT_AFFECT_START = 550;
const BYTE SPECIALSTAT_MAX_LEVEL = 15;

enum SPECIALSTAT_BOOK {
	SPECIALSTAT1,
	SPECIALSTAT2,
	SPECIALSTAT3,
	SPECIALSTAT4,
	SPECIALSTAT5,
	SPECIALSTAT6,
	SPECIALSTATS_MAX,
};

enum FROZEN_SYSTEM_BONUS {
	FROZEN_ITEM_VNUM = 58500,
	UNFROZEN_ITEM_VNUM,
	UNFROZEN_ITEM_VNUM_2,
};

#ifdef CHANGELOOK_SYSTEM
enum EChangeLookInfo
{
	CL_WINDOW_MAX_MATERIALS = 3,
	CL_CLEAN_ATTR_VALUE0 = 8,
	CL_TRANSMUTATION_PRICE = 50000000,
	CL_SCROLL_VNUM = 72325,
};
#endif

enum EWearPositions
{
	WEAR_BODY,		// 0
	WEAR_HEAD,		// 1
	WEAR_FOOTS,		// 2
	WEAR_WRIST,		// 3
	WEAR_WEAPON,	// 4
	WEAR_NECK,		// 5
	WEAR_EAR,		// 6
	WEAR_UNIQUE1,	// 7
	WEAR_UNIQUE2,	// 8
	WEAR_ARROW,		// 9
	WEAR_SHIELD,	// 10
    WEAR_ABILITY1,  // 11
    WEAR_ABILITY2,  // 12
    WEAR_ABILITY3,  // 13
    WEAR_ABILITY4,  // 14
    WEAR_ABILITY5,  // 15
    WEAR_ABILITY6,  // 16
    WEAR_ABILITY7,  // 17
    WEAR_ABILITY8,  // 18
	WEAR_COSTUME_BODY,	// 19
	WEAR_COSTUME_HAIR,	// 20

#ifdef ENABLE_MOUNT_COSTUME_SYSTEM
	WEAR_COSTUME_MOUNT,
#else
	WEAR_RING1,			// 21	: �ű� ��������1 (����)
#endif
#ifdef ENABLE_ACCE_COSTUME_SYSTEM
	WEAR_COSTUME_ACCE,
#else
	WEAR_RING2,			// 22	: �ű� ��������2 (������)
#endif

	WEAR_BELT,			// 23	: �ű� ��Ʈ����

#ifdef ENABLE_WEAPON_COSTUME_SYSTEM
	WEAR_COSTUME_WEAPON, //24
#endif
#ifdef ENABLE_NEW_TALISMAN_GF
	WEAR_TALISMAN,		//25
#endif
#if defined(ENABLE_NEW_TALISMAN_SLOTS_NEW) || defined(ENABLE_NEW_TALISMAN_SLOTS)
	WEAR_TALISMAN_2,		//26
	WEAR_TALISMAN_3,		//27
	WEAR_TALISMAN_4,		//28
	WEAR_TALISMAN_5,		//29
	WEAR_TALISMAN_6,		//30
#endif
#ifdef ENABLE_AURA_SYSTEM
	WEAR_COSTUME_AURA,		//31
#endif
#ifdef ENABLE_EFFECT_COSTUME_SYSTEM
	WEAR_COSTUME_EFFECT, //32
#endif
#ifdef NEW_RING_SLOT
	WEAR_RING_NEW,	//33
#endif

#ifdef ENABLE_SYSTEM_RUNE
	WEAR_RUNE,
	WEAR_RUNE_RED,
	WEAR_RUNE_BLUE,
	WEAR_RUNE_GREEN,
	WEAR_RUNE_YELLOW,
	WEAR_RUNE_BLACK,
#endif

#if defined(ENABLE_NEW_TALISMAN_SLOTS_NEW) || defined(ENABLE_NEW_TALISMAN_SLOTS)
	WEAR_MAX = 60
#else
	WEAR_MAX = 32	//
#endif

};

enum EDragonSoulDeckType
{
	DRAGON_SOUL_DECK_0,
	DRAGON_SOUL_DECK_1,
	DRAGON_SOUL_DECK_MAX_NUM = 2,

	DRAGON_SOUL_DECK_RESERVED_MAX_NUM = 3,	// NOTE: �߿�! ���� ��������� ������, 3������ �з��� ���� �� ��. DS DECK�� �ø� ��� �ݵ�� �� ����ŭ RESERVED���� �����ؾ� ��!
};

enum ESex
{
	SEX_MALE,
	SEX_FEMALE
};

enum EDirection
{
	DIR_NORTH,
	DIR_NORTHEAST,
	DIR_EAST,
	DIR_SOUTHEAST,
	DIR_SOUTH,
	DIR_SOUTHWEST,
	DIR_WEST,
	DIR_NORTHWEST,
	DIR_MAX_NUM
};

#define ABILITY_MAX_LEVEL	10  /* ��� �ִ� ���� */

enum EAbilityDifficulty
{
	DIFFICULTY_EASY,
	DIFFICULTY_NORMAL,
	DIFFICULTY_HARD,
	DIFFICULTY_VERY_HARD,
	DIFFICULTY_NUM_TYPES
};

enum EAbilityCategory
{
	CATEGORY_PHYSICAL,	/* ��ü�� �����Ƽ */
	CATEGORY_MENTAL,	/* ������ �����Ƽ */
	CATEGORY_ATTRIBUTE,	/* �ɷ� �����Ƽ */
	CATEGORY_NUM_TYPES
};

enum EJobs
{
	JOB_WARRIOR,
	JOB_ASSASSIN,
	JOB_SURA,
	JOB_SHAMAN,
#ifdef ENABLE_WOLFMAN_CHARACTER
	JOB_WOLFMAN,		// ������. �����ڵ���� WOLFMAN. (��ȹ�ڰ� ���߾�. ���߿� WOLF GIRL ���ܵ� ������ �Ӷ����������Ф�)
#endif
	JOB_MAX_NUM
};

enum ESkillGroups
{
	SKILL_GROUP_MAX_NUM = 2,
};

enum ERaceFlags
{
	RACE_FLAG_ANIMAL	= (1 << 0),
	RACE_FLAG_UNDEAD	= (1 << 1),
	RACE_FLAG_DEVIL		= (1 << 2),
	RACE_FLAG_HUMAN		= (1 << 3),
	RACE_FLAG_ORC		= (1 << 4),
	RACE_FLAG_MILGYO	= (1 << 5),
	RACE_FLAG_INSECT	= (1 << 6),
	RACE_FLAG_FIRE		= (1 << 7),
	RACE_FLAG_ICE		= (1 << 8),
	RACE_FLAG_DESERT	= (1 << 9),
	RACE_FLAG_TREE		= (1 << 10),
#ifdef ENABLE_NEW_TALISMAN_GF
	RACE_FLAG_ELEC		= (1 << 11),
	RACE_FLAG_WIND		= (1 << 12),
	RACE_FLAG_EARTH		= (1 << 13),
	RACE_FLAG_DARK		= (1 << 14),
	RACE_FLAG_ATT_ELEC	= (1 << 15),
	RACE_FLAG_ATT_FIRE	= (1 << 16),
	RACE_FLAG_ATT_ICE	= (1 << 17),
	RACE_FLAG_ATT_WIND	= (1 << 18),
	RACE_FLAG_ATT_EARTH	= (1 << 19),
	RACE_FLAG_ATT_DARK	= (1 << 20),
	RACE_FLAG_ATT_ZODIAC	= (1 << 21),
	RACE_FLAG_ATT_DESERT	= (1 << 22),
	RACE_FLAG_ATT_INSECT	= (1 << 23),
#endif
};

enum EGuildWarFlags
{
	GWAR_FLAG_DUMMY			= (1 << 0),
	GWAR_FLAG_CAN_OBSERVER	= (1 << 1),
};

enum ELoads
{
	LOAD_NONE,
	LOAD_LIGHT,
	LOAD_NORMAL,
	LOAD_HEAVY,
	LOAD_MASSIVE
};

enum
{
	QUICKSLOT_TYPE_NONE,
	QUICKSLOT_TYPE_ITEM,
	QUICKSLOT_TYPE_SKILL,
	QUICKSLOT_TYPE_COMMAND,
	QUICKSLOT_TYPE_MAX_NUM,
};

enum EParts
{
	PART_MAIN,
	PART_WEAPON,
	PART_HEAD,
	PART_HAIR,
#ifdef ENABLE_ACCE_COSTUME_SYSTEM
	PART_ACCE,
#endif
#ifdef __NEW_ARROW_SYSTEM__
	PART_ARROW_TYPE,
#endif
#ifdef ENABLE_AURA_SYSTEM
	PART_AURA,
#endif
#ifdef ENABLE_EFFECT_COSTUME_SYSTEM
	PART_EFFECT,
#endif
	PART_MAX_NUM,
	PART_WEAPON_SUB,
};

enum EChatType
{
	CHAT_TYPE_TALKING,	/* �׳� ä�� */
	CHAT_TYPE_INFO,	/* ���� (�������� ������, ����ġ�� �����. ��) */
	CHAT_TYPE_NOTICE,	/* �������� */
	CHAT_TYPE_PARTY,	/* ��Ƽ�� */
	CHAT_TYPE_GUILD,	/* ��帻 */
	CHAT_TYPE_COMMAND,	/* �Ϲ� ���� */
	CHAT_TYPE_SHOUT,	/* ��ġ�� */
	CHAT_TYPE_WHISPER,
	CHAT_TYPE_BIG_NOTICE,
	CHAT_TYPE_MONARCH_NOTICE,
	// CHAT_TYPE_UNK_10,
#ifdef ENABLE_DICE_SYSTEM
	CHAT_TYPE_DICE_INFO, //11
#endif
#if defined(__CHATTING_WINDOW_RENEWAL__)
	CHAT_TYPE_EXP_INFO,
	CHAT_TYPE_ITEM_INFO,
	CHAT_TYPE_MONEY_INFO,
#endif
	CHAT_TYPE_MISSION,
	CHAT_TYPE_MAX_NUM
};

enum EWhisperType
{
	WHISPER_TYPE_NORMAL		= 0,
	WHISPER_TYPE_NOT_EXIST		= 1,
	WHISPER_TYPE_TARGET_BLOCKED	= 2,
	WHISPER_TYPE_SENDER_BLOCKED	= 3,
	WHISPER_TYPE_ERROR		= 4,
	WHISPER_TYPE_GM			= 5,
	WHISPER_TYPE_SYSTEM		= 0xFF
};

enum ECharacterPosition
{
	POSITION_GENERAL,
	POSITION_BATTLE,
	POSITION_DYING,
	POSITION_SITTING_CHAIR,
	POSITION_SITTING_GROUND,
	POSITION_INTRO,
	POSITION_MAX_NUM
};

enum EGMLevels
{
	GM_PLAYER,
	GM_LOW_WIZARD,
	GM_WIZARD,
	GM_HIGH_WIZARD,
	GM_GOD,
	GM_IMPLEMENTOR,
	GM_DISABLE,
};

enum EMobRank
{
	MOB_RANK_PAWN,
	MOB_RANK_S_PAWN,
	MOB_RANK_KNIGHT,
	MOB_RANK_S_KNIGHT,
	MOB_RANK_BOSS,
	MOB_RANK_KING,
	MOB_RANK_MAX_NUM
};

enum ECharType
{
	CHAR_TYPE_MONSTER,
	CHAR_TYPE_NPC,
	CHAR_TYPE_STONE,
	CHAR_TYPE_WARP,
	CHAR_TYPE_DOOR,
	CHAR_TYPE_BUILDING,
	CHAR_TYPE_PC,
	CHAR_TYPE_POLYMORPH_PC,
	CHAR_TYPE_HORSE,
	CHAR_TYPE_GOTO,
	CHAR_TYPE_PET
};

enum EBattleType
{
	BATTLE_TYPE_MELEE,
	BATTLE_TYPE_RANGE,
	BATTLE_TYPE_MAGIC,
	BATTLE_TYPE_SPECIAL,
	BATTLE_TYPE_POWER,
	BATTLE_TYPE_TANKER,
	BATTLE_TYPE_SUPER_POWER,
	BATTLE_TYPE_SUPER_TANKER,
	BATTLE_TYPE_MAX_NUM
};

enum EApplyTypes
{
	APPLY_NONE,			// 0
	APPLY_MAX_HP,		// 1
	APPLY_MAX_SP,		// 2
	APPLY_CON,			// 3
	APPLY_INT,			// 4
	APPLY_STR,			// 5
	APPLY_DEX,			// 6
	APPLY_ATT_SPEED,	// 7
	APPLY_MOV_SPEED,	// 8
	APPLY_CAST_SPEED,	// 9
	APPLY_HP_REGEN,		// 10
	APPLY_SP_REGEN,		// 11
	APPLY_POISON_PCT,	// 12
	APPLY_STUN_PCT,		// 13
	APPLY_SLOW_PCT,		// 14
	APPLY_CRITICAL_PCT,		// 15
	APPLY_PENETRATE_PCT,	// 16
	APPLY_ATTBONUS_HUMAN,	// 17
	APPLY_ATTBONUS_ANIMAL,	// 18
	APPLY_ATTBONUS_ORC,		// 19
	APPLY_ATTBONUS_MILGYO,	// 20
	APPLY_ATTBONUS_UNDEAD,	// 21
	APPLY_ATTBONUS_DEVIL,	// 22
	APPLY_STEAL_HP,			// 23
	APPLY_STEAL_SP,			// 24
	APPLY_MANA_BURN_PCT,	// 25
	APPLY_DAMAGE_SP_RECOVER,	// 26
	APPLY_BLOCK,			// 27
	APPLY_DODGE,			// 28
	APPLY_RESIST_SWORD,		// 29
	APPLY_RESIST_TWOHAND,	// 30
	APPLY_RESIST_DAGGER,	// 31
	APPLY_RESIST_BELL,		// 32
	APPLY_RESIST_FAN,		// 33
	APPLY_RESIST_BOW,		// 34
	APPLY_RESIST_FIRE,		// 35
	APPLY_RESIST_ELEC,		// 36
	APPLY_RESIST_MAGIC,		// 37
	APPLY_RESIST_WIND,		// 38
	APPLY_REFLECT_MELEE,	// 39
	APPLY_REFLECT_CURSE,	// 40
	APPLY_POISON_REDUCE,	// 41
	APPLY_KILL_SP_RECOVER,	// 42
	APPLY_EXP_DOUBLE_BONUS,	// 43
	APPLY_GOLD_DOUBLE_BONUS,	// 44
	APPLY_ITEM_DROP_BONUS,	// 45
	APPLY_POTION_BONUS,		// 46
	APPLY_KILL_HP_RECOVER,	// 47
	APPLY_IMMUNE_STUN,		// 48
	APPLY_IMMUNE_SLOW,		// 49
	APPLY_IMMUNE_FALL,		// 50
	APPLY_SKILL,			// 51
	APPLY_BOW_DISTANCE,		// 52
	APPLY_ATT_GRADE_BONUS,	// 53
	APPLY_DEF_GRADE_BONUS,	// 54
	APPLY_MAGIC_ATT_GRADE,	// 55
	APPLY_MAGIC_DEF_GRADE,	// 56
	APPLY_CURSE_PCT,		// 57
	APPLY_MAX_STAMINA,		// 58
	APPLY_ATTBONUS_WARRIOR,	// 59
	APPLY_ATTBONUS_ASSASSIN,	// 60
	APPLY_ATTBONUS_SURA,	// 61
	APPLY_ATTBONUS_SHAMAN,	// 62
	APPLY_ATTBONUS_MONSTER,	// 63
	APPLY_MALL_ATTBONUS,			// 64 ���ݷ� +x%
	APPLY_MALL_DEFBONUS,			// 65 ���� +x%
	APPLY_MALL_EXPBONUS,			// 66 ����ġ +x%
	APPLY_MALL_ITEMBONUS,			// 67 ������ ����� x/10��
	APPLY_MALL_GOLDBONUS,			// 68 �� ����� x/10��
	APPLY_MAX_HP_PCT,				// 69 �ִ� ������ +x%
	APPLY_MAX_SP_PCT,				// 70 �ִ� ���ŷ� +x%
	APPLY_SKILL_DAMAGE_BONUS,		// 71 ��ų ������ * (100+x)%
	APPLY_NORMAL_HIT_DAMAGE_BONUS,	// 72 ��Ÿ ������ * (100+x)%
	APPLY_SKILL_DEFEND_BONUS,		// 73 ��ų ������ ��� * (100-x)%
	APPLY_NORMAL_HIT_DEFEND_BONUS,	// 74 ��Ÿ ������ ��� * (100-x)%
	APPLY_PC_BANG_EXP_BONUS,		// 75 PC�� ������ EXP ���ʽ�
	APPLY_PC_BANG_DROP_BONUS,		// 76 PC�� ������ ����� ���ʽ�

	APPLY_EXTRACT_HP_PCT,			// 77 ���� HP �Ҹ�

	APPLY_RESIST_WARRIOR,			// 78 ���翡�� ����
	APPLY_RESIST_ASSASSIN,			// 79 �ڰ����� ����
	APPLY_RESIST_SURA,				// 80 ���󿡰� ����
	APPLY_RESIST_SHAMAN,			// 81 ���翡�� ����
	APPLY_ENERGY,					// 82 ���
	APPLY_DEF_GRADE,				// 83 ����. DEF_GRADE_BONUS�� Ŭ�󿡼� �ι�� �������� �ǵ��� ����(...)�� �ִ�.
	APPLY_COSTUME_ATTR_BONUS,		// 84 �ڽ�Ƭ �����ۿ� ���� �Ӽ�ġ ���ʽ�
	APPLY_MAGIC_ATTBONUS_PER,		// 85 ���� ���ݷ� +x%
	APPLY_MELEE_MAGIC_ATTBONUS_PER,			// 86 ���� + �и� ���ݷ� +x%

	APPLY_RESIST_ICE,		// 87 �ñ� ����
	APPLY_RESIST_EARTH,		// 88 ���� ����
	APPLY_RESIST_DARK,		// 89 ��� ����

	APPLY_ANTI_CRITICAL_PCT,	//90 ũ��Ƽ�� ����
	APPLY_ANTI_PENETRATE_PCT,	//91 ����Ÿ�� ����

#ifdef ENABLE_WOLFMAN_CHARACTER
	APPLY_BLEEDING_REDUCE			= 92,		//92
	APPLY_BLEEDING_PCT				= 93,		//93
	APPLY_ATTBONUS_WOLFMAN			= 94,		//94 ���������� ����
	APPLY_RESIST_WOLFMAN			= 95,		//95 ���������� ����
	APPLY_RESIST_CLAW				= 96,		//96 CLAW���⿡ ����
#endif

#ifdef ENABLE_ACCE_COSTUME_SYSTEM
	APPLY_ACCEDRAIN_RATE			= 97,			//97
#endif

#ifdef ENABLE_MAGIC_REDUCTION_SYSTEM
	APPLY_RESIST_MAGIC_REDUCTION	= 98,	//98
#endif
#ifdef ENABLE_NEW_TALISMAN_GF
	APPLY_ATTBONUS_ELEC 	= 99, 	// 99
	APPLY_ATTBONUS_FIRE		= 100, 	// 100
	APPLY_ATTBONUS_ICE		= 101, 	// 101
	APPLY_ATTBONUS_WIND		= 102, 	// 102
	APPLY_ATTBONUS_EARTH	= 103, 	// 103
	APPLY_ATTBONUS_DARK		= 104, 	// 104
	APPLY_RESIST_HUMAN, // 105

	APPLY_RESIST_SWORD_REDUCTION, //106		
	APPLY_RESIST_TWOHAND_REDUCTION, //107
	APPLY_RESIST_DAGGER_REDUCTION,	//108
	APPLY_RESIST_BELL_REDUCTION, //109		
	APPLY_RESIST_FAN_REDUCTION, //110		
	APPLY_RESIST_BOW_REDUCTION, //111

	APPLY_ATTBONUS_ZODIAC, //112
	APPLY_ATTBONUS_DESERT, //113
	APPLY_ATTBONUS_INSECT, //114	
#ifdef ENABLE_WOLFMAN_CHARACTER
	APPLY_RESIST_CLAW_REDUCTION, //115
#endif
#endif
#ifdef ENABLE_BONUS_BOSS
	APPLY_ATTBONUS_BOSS,//116
#endif
#ifdef ENABLE_BONUS_METIN
	APPLY_ATTBONUS_METIN,
#endif
	MAX_APPLY_NUM,
};

enum EOnClickEvents
{
	ON_CLICK_NONE,
	ON_CLICK_SHOP,
	ON_CLICK_TALK,
	ON_CLICK_MAX_NUM
};

enum EOnIdleEvents
{
	ON_IDLE_NONE,
	ON_IDLE_GENERAL,
	ON_IDLE_MAX_NUM
};

enum EWindows
{
	RESERVED_WINDOW,
	INVENTORY,
	EQUIPMENT,
	SAFEBOX,
	MALL,
	DRAGON_SOUL_INVENTORY,
#ifdef __SPECIAL_STORAGE_SYSTEM__
	SKILLBOOK_INVENTORY,
	UPPITEM_INVENTORY,
	GHOSTSTONE_INVENTORY,
	GENERAL_INVENTORY,
#endif
	BELT_INVENTORY,
#ifdef ENABLE_SWITCHBOT
	SWITCHBOT,
#endif
#ifdef __AUCTION__
	AUCTION,
#endif
#ifdef ENABLE_6_7_BONUS_NEW_SYSTEM
	BONUS_NEW_67,
#endif
#ifdef FAST_EQUIP_WORLDARD
	CHANGE_EQUIP,
#endif
	GROUND
};

enum EMobSizes
{
	MOBSIZE_RESERVED,
	MOBSIZE_SMALL,
	MOBSIZE_MEDIUM,
	MOBSIZE_BIG
};

enum EAIFlags
{
	AIFLAG_AGGRESSIVE	= (1 << 0),
	AIFLAG_NOMOVE	= (1 << 1),
	AIFLAG_COWARD	= (1 << 2),
	AIFLAG_NOATTACKSHINSU	= (1 << 3),
	AIFLAG_NOATTACKJINNO	= (1 << 4),
	AIFLAG_NOATTACKCHUNJO	= (1 << 5),
	AIFLAG_ATTACKMOB = (1 << 6 ),
	AIFLAG_BERSERK	= (1 << 7),
	AIFLAG_STONESKIN	= (1 << 8),
	AIFLAG_GODSPEED	= (1 << 9),
	AIFLAG_DEATHBLOW	= (1 << 10),
	AIFLAG_REVIVE		= (1 << 11),
};

enum EMobStatType
{
	MOB_STATTYPE_POWER,
	MOB_STATTYPE_TANKER,
	MOB_STATTYPE_SUPER_POWER,
	MOB_STATTYPE_SUPER_TANKER,
	MOB_STATTYPE_RANGE,
	MOB_STATTYPE_MAGIC,
	MOB_STATTYPE_MAX_NUM
};

enum EImmuneFlags
{
	IMMUNE_STUN		= (1 << 0),
	IMMUNE_SLOW		= (1 << 1),
	IMMUNE_FALL		= (1 << 2),
	IMMUNE_CURSE	= (1 << 3),
	IMMUNE_POISON	= (1 << 4),
	IMMUNE_TERROR	= (1 << 5),
	IMMUNE_REFLECT	= (1 << 6),
};

enum EMobEnchants
{
	MOB_ENCHANT_CURSE,
	MOB_ENCHANT_SLOW,
	MOB_ENCHANT_POISON,
	MOB_ENCHANT_STUN,
	MOB_ENCHANT_CRITICAL,
	MOB_ENCHANT_PENETRATE,
#if defined(ENABLE_WOLFMAN_CHARACTER) && !defined(USE_MOB_BLEEDING_AS_POISON)
	MOB_ENCHANT_BLEEDING,
#endif
	MOB_ENCHANTS_MAX_NUM
};

enum EMobResists
{
	MOB_RESIST_SWORD,
	MOB_RESIST_TWOHAND,
	MOB_RESIST_DAGGER,
	MOB_RESIST_BELL,
	MOB_RESIST_FAN,
	MOB_RESIST_BOW,
	MOB_RESIST_FIRE,
	MOB_RESIST_ELECT,
	MOB_RESIST_MAGIC,
	MOB_RESIST_WIND,
	MOB_RESIST_POISON,
#if defined(ENABLE_WOLFMAN_CHARACTER) && !defined(USE_MOB_CLAW_AS_DAGGER)
	MOB_RESIST_CLAW,
#endif
#if defined(ENABLE_WOLFMAN_CHARACTER) && !defined(USE_MOB_BLEEDING_AS_POISON)
	MOB_RESIST_BLEEDING,
#endif
	MOB_RESISTS_MAX_NUM
};

enum
{
	SKILL_ATTR_TYPE_NORMAL = 1,
	SKILL_ATTR_TYPE_MELEE,
	SKILL_ATTR_TYPE_RANGE,
	SKILL_ATTR_TYPE_MAGIC
		/*
		   SKILL_ATTR_TYPE_FIRE,
		   SKILL_ATTR_TYPE_ICE,
		   SKILL_ATTR_TYPE_ELEC,
		   SKILL_ATTR_TYPE_DARK,
		   */
};

enum
{
	SKILL_NORMAL,
	SKILL_MASTER,
	SKILL_GRAND_MASTER,
	SKILL_PERFECT_MASTER,
};

enum EGuildWarType
{
	GUILD_WAR_TYPE_FIELD,
	GUILD_WAR_TYPE_BATTLE,
	GUILD_WAR_TYPE_FLAG,
	GUILD_WAR_TYPE_MAX_NUM
};

enum EGuildWarState
{
	GUILD_WAR_NONE,
	GUILD_WAR_SEND_DECLARE,
	GUILD_WAR_REFUSE,
	GUILD_WAR_RECV_DECLARE,
	GUILD_WAR_WAIT_START,
	GUILD_WAR_CANCEL,
	GUILD_WAR_ON_WAR,
	GUILD_WAR_END,
	GUILD_WAR_OVER,
	GUILD_WAR_RESERVE,

	GUILD_WAR_DURATION = 30*60, // 1�ð�
	GUILD_WAR_WIN_POINT = 1000,
	GUILD_WAR_LADDER_HALF_PENALTY_TIME = 12*60*60,
};

enum EChannel
{
    GUILD_WARP_WAR_CHANNEL = 98,
    CHANNEL_SINGLE_MAPS = 99
};

enum EAttributeSet
{
	ATTRIBUTE_SET_WEAPON,
	ATTRIBUTE_SET_BODY,
	ATTRIBUTE_SET_WRIST,
	ATTRIBUTE_SET_FOOTS,
	ATTRIBUTE_SET_NECK,
	ATTRIBUTE_SET_HEAD,
	ATTRIBUTE_SET_SHIELD,
	ATTRIBUTE_SET_EAR,
#ifdef ENABLE_NEW_TALISMAN_GF
	ATTRIBUTE_SET_TALISMAN,
#endif
#if defined(ENABLE_NEW_TALISMAN_SLOTS_NEW) || defined(ENABLE_NEW_TALISMAN_SLOTS)
	ATTRIBUTE_SET_TALISMAN_2,
	ATTRIBUTE_SET_TALISMAN_3,
	ATTRIBUTE_SET_TALISMAN_4,
	ATTRIBUTE_SET_TALISMAN_5,
	ATTRIBUTE_SET_TALISMAN_6,
#endif
	ATTRIBUTE_SET_MAX_NUM
};

enum EPrivType
{
	PRIV_NONE,
	PRIV_ITEM_DROP,
	PRIV_GOLD_DROP,
	PRIV_GOLD10_DROP,
	PRIV_EXP_PCT,
#ifdef ENABLE_DECORUM
	PRIV_DECORUM_GAIN,
#endif	
	MAX_PRIV_NUM,
};

enum EMoneyLogType
{
	MONEY_LOG_RESERVED,
	MONEY_LOG_MONSTER,
	MONEY_LOG_SHOP,
	MONEY_LOG_REFINE,
	MONEY_LOG_QUEST,
	MONEY_LOG_GUILD,
	MONEY_LOG_MISC,
	MONEY_LOG_MONSTER_KILL,
	MONEY_LOG_DROP,
	MONEY_LOG_TYPE_MAX_NUM,
};

enum EPremiumTypes
{
	PREMIUM_EXP,		// ����ġ�� 1.2��
	PREMIUM_ITEM,		// ������ ������� 2��
	PREMIUM_SAFEBOX,		// â���� 1ĭ���� 3ĭ
	PREMIUM_AUTOLOOT,		// �� �ڵ� �ݱ�
	PREMIUM_FISH_MIND,		// ���� ������ ���� Ȯ�� ���
	PREMIUM_MARRIAGE_FAST,	// �ݽ� ���� ���� �������մϴ�.
	PREMIUM_GOLD,		// �� ������� 1.5��
	PREMIUM_MAX_NUM = 9
};

#ifdef ITEM_BUFF_SYSTEM
enum EItemBuffConfig
{
	
//first item resist buff config	
	MASTER_RESIST_BLESS_ITEM_BUFF_VNUM = 79000,
	MASTER_RESIST_BLESS_AFFECT_VALUE = 24,
	MASTER_RESIST_BLESS_AFFECT_TIME_VALUE = 250,	
	MASTER_RESIST_BLESS_USINGS = 80,
// end of first item resist buff config

//secound item resist buff config	
	GRAND_RESIST_BLESS_ITEM_BUFF_VNUM = 79001,
	GRAND_RESIST_BLESS_AFFECT_VALUE = 29,
	GRAND_RESIST_BLESS_AFFECT_TIME_VALUE = 350,	
	GRAND_RESIST_BLESS_USINGS = 100,
//end of second item resist buff config	

//third item resist buff config	
	PERFECT_RESIST_BLESS_ITEM_BUFF_VNUM = 79002,
	PERFECT_RESIST_BLESS_AFFECT_VALUE = 35,
	PERFECT_RESIST_BLESS_AFFECT_TIME_VALUE = 500,	
	PERFECT_RESIST_BLESS_USINGS = 120,
//end of third item resist buff config	

//first item critical buff config
	MASTER_CRITICAL_BLESS_ITEM_BUFF_VNUM = 79003,
	MASTER_CRITICAL_BLESS_AFFECT_VALUE = 24,
	MASTER_CRITICAL_BLESS_AFFECT_TIME_VALUE = 250,	
	MASTER_CRITICAL_BLESS_USINGS = 80,
//end of first item critical buff config

//secound item critical buff config	
	GRAND_CRITICAL_BLESS_ITEM_BUFF_VNUM = 79004,
	GRAND_CRITICAL_BLESS_AFFECT_VALUE = 29,
	GRAND_CRITICAL_BLESS_AFFECT_TIME_VALUE = 350,	
	GRAND_CRITICAL_BLESS_USINGS = 100,
//end of secound item critical buff config	

//third item critical buff config
	PERFECT_CRITICAL_BLESS_ITEM_BUFF_VNUM = 79005,
	PERFECT_CRITICAL_BLESS_AFFECT_VALUE = 35,
	PERFECT_CRITICAL_BLESS_AFFECT_TIME_VALUE = 500,	
	PERFECT_CRITICAL_BLESS_USINGS = 120,	
//end of third item critical buff config	

//first item reflection buff config
	MASTER_REFLECT_BLESS_ITEM_BUFF_VNUM = 79006,
	MASTER_REFLECT_BLESS_AFFECT_VALUE = 21,
	MASTER_REFLECT_BLESS_AFFECT_TIME_VALUE = 250,	
	MASTER_REFLECT_BLESS_USINGS = 80,
//end of first item reflection buff config

//secound item reflection buff config	
	GRAND_REFLECT_BLESS_ITEM_BUFF_VNUM = 79007,
	GRAND_REFLECT_BLESS_AFFECT_VALUE = 31,
	GRAND_REFLECT_BLESS_AFFECT_TIME_VALUE = 350,	
	GRAND_REFLECT_BLESS_USINGS = 100,
//end of secound item reflection buff config	

//third item reflection buff config
	PERFECT_REFLECT_BLESS_ITEM_BUFF_VNUM = 79008,
	PERFECT_REFLECT_BLESS_AFFECT_VALUE = 45,
	PERFECT_REFLECT_BLESS_AFFECT_TIME_VALUE = 500,	
	PERFECT_REFLECT_BLESS_USINGS = 120,	
//end of third item reflection buff config	

};
#endif

enum SPECIAL_EFFECT
{
	SE_NONE,

	SE_HPUP_RED,
	SE_SPUP_BLUE,
	SE_SPEEDUP_GREEN,
	SE_DXUP_PURPLE,
	SE_CRITICAL,
	SE_PENETRATE,
	SE_BLOCK,
	SE_DODGE,
	SE_CHINA_FIREWORK,
	SE_SPIN_TOP,
	SE_SUCCESS,
	SE_FAIL,
	SE_FR_SUCCESS,
	SE_LEVELUP_ON_14_FOR_GERMANY,
	SE_LEVELUP_UNDER_15_FOR_GERMANY,
	SE_PERCENT_DAMAGE1,
	SE_PERCENT_DAMAGE2,
	SE_PERCENT_DAMAGE3,

	SE_AUTO_HPUP,
	SE_AUTO_SPUP,

	SE_EQUIP_RAMADAN_RING,		// �󸶴� �ʽ´��� ����(71135) ������ �� ����Ʈ (�ߵ�����Ʈ��, ��������Ʈ �ƴ�)
	SE_EQUIP_HALLOWEEN_CANDY,		// �ҷ��� ������ ����(-_-;)�� ������ �ߵ��ϴ� ����Ʈ
	SE_EQUIP_HAPPINESS_RING,		// ũ�������� �ູ�� ����(71143) ������ �� ����Ʈ (�ߵ�����Ʈ��, ��������Ʈ �ƴ�)
	SE_EQUIP_LOVE_PENDANT,		// �߷�Ÿ�� ����� �Ҵ�Ʈ(71145) ������ �� ����Ʈ (�ߵ�����Ʈ��, ��������Ʈ �ƴ�)
#ifdef ENABLE_DUEL_EFFECT
	SE_PVP_WIN,
	SE_PVP_OPEN1,
	SE_PVP_OPEN2,
	SE_PVP_BEGIN1,
	SE_PVP_BEGIN2,
#endif
#ifdef ENABLE_AGGREGATE_MONSTER_EFFECT
	SE_AGGREGATE_MONSTER_EFFECT,
#endif

#ifdef ENABLE_ACCE_COSTUME_SYSTEM
	SE_EFFECT_ACCE_SUCCEDED,
	SE_EFFECT_ACCE_EQUIP,
#endif

#ifdef ENABLE_OVER_KILL
	SE_OVER_KILL_START,
	SE_OVER_KILL_END = SE_OVER_KILL_START + (OVER_KILL_MAX_NUM -1), //-1 because SE_OVER_KILL_START is first 
#endif
#ifdef ENABLE_TALISMAN_EFFECT
	SE_EFFECT_TALISMAN_EQUIP_FIRE,
	SE_EFFECT_TALISMAN_EQUIP_ICE,
	SE_EFFECT_TALISMAN_EQUIP_WIND,
	SE_EFFECT_TALISMAN_EQUIP_EARTH,
	SE_EFFECT_TALISMAN_EQUIP_DARK,
	SE_EFFECT_TALISMAN_EQUIP_ELEC,
#endif
#ifdef ENABLE_SYSTEM_RUNE
	SE_RUNA_WHITE_EFFECT,
	SE_RUNA_RED_EFFECT,
	SE_RUNA_BLUE_EFFECT,
	SE_RUNA_YELLOW_EFFECT,
	SE_RUNA_BLACK_EFFECT,
	SE_RUNA_GREEN_EFFECT,
#endif
};

enum ETeenFlags
{
	TEENFLAG_NONE = 0,
	TEENFLAG_1HOUR,
	TEENFLAG_2HOUR,
	TEENFLAG_3HOUR,
	TEENFLAG_4HOUR,
	TEENFLAG_5HOUR,
};

#include "item_length.h"

// inventory�� position�� ��Ÿ���� ����ü
// int���� �Ͻ��� ����ȯ�� �ִ� ������,
// �κ� ���õ� ��� �Լ��� window_type�� ���� �ʰ�, cell �ϳ��� �޾ұ� ������,(�������� �κ��� �ϳ� ���̾ inventory type�̶��� �ʿ������ ������,)
// �κ� ���� ��� �Լ� ȣ��κ��� �����ϴ� ���� �����ϱ� �����̴�.

enum EDragonSoulRefineWindowSize
{
	DRAGON_SOUL_REFINE_GRID_MAX = 15,
};

enum EMisc2
{
	DRAGON_SOUL_EQUIP_SLOT_START = INVENTORY_MAX_NUM + WEAR_MAX_NUM,
	DRAGON_SOUL_EQUIP_SLOT_END = DRAGON_SOUL_EQUIP_SLOT_START + (DS_SLOT_MAX * DRAGON_SOUL_DECK_MAX_NUM),
	DRAGON_SOUL_EQUIP_RESERVED_SLOT_END = DRAGON_SOUL_EQUIP_SLOT_END + (DS_SLOT_MAX * DRAGON_SOUL_DECK_RESERVED_MAX_NUM),

	BELT_INVENTORY_SLOT_START = DRAGON_SOUL_EQUIP_RESERVED_SLOT_END,
	BELT_INVENTORY_SLOT_END = BELT_INVENTORY_SLOT_START + BELT_INVENTORY_SLOT_COUNT,

	INVENTORY_AND_EQUIP_SLOT_MAX = BELT_INVENTORY_SLOT_END,
};

#ifdef FAST_EQUIP_WORLDARD 
enum ChangeEquipConfig
{
	CHANGE_EQUIP_PAGE_EXTRA = 10,
	CHANGE_EQUIP_SLOT_COUNT = 30*CHANGE_EQUIP_PAGE_EXTRA,
};

static const DWORD EWearCheckPositions[]=
{
	WEAR_BODY,		// 0
	WEAR_HEAD,		// 1
	WEAR_FOOTS,		// 2
	WEAR_WRIST,		// 3
	WEAR_WEAPON,	// 4
	WEAR_NECK,		// 5
	WEAR_EAR,		// 6
	WEAR_UNIQUE1,	// 7
	WEAR_UNIQUE2,	// 8
	WEAR_ARROW,		// 9
	WEAR_SHIELD,	// 10
    WEAR_ABILITY1,  // 11
    WEAR_ABILITY2,  // 12
    WEAR_ABILITY3,  // 13
    WEAR_ABILITY4,  // 14
    WEAR_ABILITY5,  // 15
    WEAR_ABILITY6,  // 16
    WEAR_ABILITY7,  // 17
    WEAR_ABILITY8,  // 18
	WEAR_COSTUME_BODY,	// 19
	WEAR_COSTUME_HAIR,	// 20
#ifdef ENABLE_WEAPON_COSTUME_SYSTEM
	WEAR_COSTUME_WEAPON,
#endif
	WEAR_BELT,			// 23
};
#endif

#pragma pack(push, 1)

typedef struct SItemPos
{
	BYTE window_type;
	WORD cell;
    SItemPos ()
    {
        window_type = INVENTORY;
		cell = WORD_MAX;
    }

	SItemPos (BYTE _window_type, WORD _cell)
    {
        window_type = _window_type;
        cell = _cell;
    }

	bool IsValidItemPosition() const
	{
		switch (window_type)
		{
		case RESERVED_WINDOW:
			return false;
		case INVENTORY:
		case EQUIPMENT:
		case BELT_INVENTORY:
			return cell < INVENTORY_AND_EQUIP_SLOT_MAX;
		case DRAGON_SOUL_INVENTORY:
			return cell < (DRAGON_SOUL_INVENTORY_MAX_NUM);
#ifdef __SPECIAL_STORAGE_SYSTEM__
			case SKILLBOOK_INVENTORY:
			case UPPITEM_INVENTORY:
			case GHOSTSTONE_INVENTORY:
			case GENERAL_INVENTORY:
				return cell < (SPECIAL_STORAGE_INVENTORY_MAX_NUM);
#endif
#ifdef ENABLE_6_7_BONUS_NEW_SYSTEM
			case BONUS_NEW_67:
				return cell < BONUS_67_SLOT_MAX;
#endif
#ifdef FAST_EQUIP_WORLDARD
		case CHANGE_EQUIP:
			return cell < CHANGE_EQUIP_SLOT_COUNT;
#endif
		// �������� ũ�Ⱑ �������� window�� valid üũ�� �� ���� ����.
		case SAFEBOX:
		case MALL:
			return false;
#ifdef ENABLE_SWITCHBOT
		case SWITCHBOT:
			return cell < SWITCHBOT_SLOT_COUNT;
#endif
		default:
			return false;
		}
		return false;
	}

	bool IsEquipPosition() const
	{
		return ((INVENTORY == window_type || EQUIPMENT == window_type) && cell >= INVENTORY_MAX_NUM && cell < INVENTORY_MAX_NUM + WEAR_MAX_NUM)
			|| IsDragonSoulEquipPosition();
	}

	bool IsDragonSoulEquipPosition() const
	{
		return (window_type == INVENTORY) && (DRAGON_SOUL_EQUIP_SLOT_START <= cell) && (DRAGON_SOUL_EQUIP_SLOT_END > cell);
	}

	bool IsBeltInventoryPosition() const
	{
		return (BELT_INVENTORY_SLOT_START <= cell) && (BELT_INVENTORY_SLOT_END > cell);
	}

	bool IsDefaultInventoryPosition() const
	{
		return INVENTORY == window_type && cell < INVENTORY_MAX_NUM;
	}

#ifdef ENABLE_SWITCHBOT
	bool IsSwitchbotPosition() const
	{
		return SWITCHBOT == window_type && cell < SWITCHBOT_SLOT_COUNT;
	}
#endif

#ifdef FAST_EQUIP_WORLDARD
	bool IsChangeEquipPosition() const
	{
		return CHANGE_EQUIP == window_type && cell < CHANGE_EQUIP_SLOT_COUNT;
	}
#endif

	bool operator==(const struct SItemPos& rhs) const
	{
		return (window_type == rhs.window_type) && (cell == rhs.cell);
	}
	bool operator<(const struct SItemPos& rhs) const
	{
		return (window_type < rhs.window_type) || ((window_type == rhs.window_type) && (cell < rhs.cell));
	}
} TItemPos;

const TItemPos NPOS (RESERVED_WINDOW, WORD_MAX);

typedef enum
{
	SHOP_COIN_TYPE_GOLD, // DEFAULT VALUE
	SHOP_COIN_TYPE_SECONDARY_COIN,
} EShopCoinType;

#ifdef ENABLE_ANTI_MULTIPLE_FARM
enum EAntiMultipleFarmConfigs
{
	MA_LENGTH = 255,
	MULTIPLE_FARM_MAX_ACCOUNT = 2,
};
#endif

#pragma pack(pop)

#endif
